/**
 * Mock data for the Compliance & KYC page.
 * Values match the HTML prototype exactly.
 */

import type {
  ComplianceStats,
  SellerCompliance,
  DocumentQueueItem,
} from '../types';

export const mockComplianceStats: ComplianceStats = {
  totalSellers: 234,
  fullyCompliant: 180,
  fullyCompliantPercent: '76.9%',
  partiallyCompliant: 36,
  partiallyCompliantPercent: '15.4%',
  nonCompliant: 18,
  nonCompliantPercent: '7.7%',
  pendingReview: 12,
};

export const mockSellerCompliance: SellerCompliance[] = [
  {
    id: 'sc-001',
    sellerId: 'SLR-001',
    sellerName: 'Rajesh Sharma',
    initials: 'RS',
    avatarBg: 'bg-orange-100',
    avatarText: 'text-orange-600',
    storeName: 'TechHub Electronics',
    gstStatus: 'Verified',
    panStatus: 'Verified',
    bankVerified: 'verified',
    docsCompleted: 5,
    docsTotal: 5,
    overallStatus: 'Fully Compliant',
    actions: ['Review'],
  },
  {
    id: 'sc-002',
    sellerId: 'SLR-002',
    sellerName: 'Anita Patel',
    initials: 'AP',
    avatarBg: 'bg-purple-100',
    avatarText: 'text-purple-600',
    storeName: 'Fashion Fiesta',
    gstStatus: 'Verified',
    panStatus: 'Verified',
    bankVerified: 'verified',
    docsCompleted: 5,
    docsTotal: 5,
    overallStatus: 'Fully Compliant',
    actions: ['Review'],
  },
  {
    id: 'sc-003',
    sellerId: 'SLR-003',
    sellerName: 'Vikram Kumar',
    initials: 'VK',
    avatarBg: 'bg-blue-100',
    avatarText: 'text-blue-600',
    storeName: 'GreenLeaf Organics',
    gstStatus: 'Pending',
    panStatus: 'Verified',
    bankVerified: 'verified',
    docsCompleted: 3,
    docsTotal: 5,
    overallStatus: 'Partially Compliant',
    actions: ['Review', 'Approve'],
  },
  {
    id: 'sc-004',
    sellerId: 'SLR-004',
    sellerName: 'Meera Joshi',
    initials: 'MJ',
    avatarBg: 'bg-red-100',
    avatarText: 'text-red-600',
    storeName: 'HomeStyle Decor',
    gstStatus: 'Expired',
    panStatus: 'Pending',
    bankVerified: 'rejected',
    docsCompleted: 1,
    docsTotal: 5,
    overallStatus: 'Non-Compliant',
    actions: ['Review', 'Reject'],
  },
  {
    id: 'sc-005',
    sellerId: 'SLR-005',
    sellerName: 'Suresh Krishnan',
    initials: 'SK',
    avatarBg: 'bg-teal-100',
    avatarText: 'text-teal-600',
    storeName: 'SpiceLand Traders',
    gstStatus: 'Verified',
    panStatus: 'Verified',
    bankVerified: 'pending',
    docsCompleted: 4,
    docsTotal: 5,
    overallStatus: 'Partially Compliant',
    actions: ['Review', 'Approve'],
  },
  {
    id: 'sc-006',
    sellerId: 'SLR-006',
    sellerName: 'Deepa Agarwal',
    initials: 'DA',
    avatarBg: 'bg-orange-100',
    avatarText: 'text-orange-600',
    storeName: 'CraftVilla Artisans',
    gstStatus: 'Expired',
    panStatus: 'Expired',
    bankVerified: 'rejected',
    docsCompleted: 0,
    docsTotal: 5,
    overallStatus: 'Non-Compliant',
    actions: ['Review', 'Reject'],
  },
  {
    id: 'sc-007',
    sellerId: 'SLR-007',
    sellerName: 'Priya Nair',
    initials: 'PN',
    avatarBg: 'bg-indigo-100',
    avatarText: 'text-indigo-600',
    storeName: 'BookWorm Paradise',
    gstStatus: 'Verified',
    panStatus: 'Verified',
    bankVerified: 'verified',
    docsCompleted: 5,
    docsTotal: 5,
    overallStatus: 'Fully Compliant',
    actions: ['Review'],
  },
  {
    id: 'sc-008',
    sellerId: 'SLR-008',
    sellerName: 'Arjun Mehta',
    initials: 'AM',
    avatarBg: 'bg-pink-100',
    avatarText: 'text-pink-600',
    storeName: 'FitGear Sports',
    gstStatus: 'Verified',
    panStatus: 'Pending',
    bankVerified: 'verified',
    docsCompleted: 3,
    docsTotal: 5,
    overallStatus: 'Partially Compliant',
    actions: ['Review', 'Approve'],
  },
];

export const mockDocumentQueue: DocumentQueueItem[] = [
  {
    id: 'doc-001',
    documentName: 'GST Certificate',
    sellerInfo: 'Vikram Kumar (GreenLeaf Organics)',
    uploadDate: 'Mar 25, 2026',
    iconColor: 'blue',
  },
  {
    id: 'doc-002',
    documentName: 'PAN Card',
    sellerInfo: 'Meera Joshi (HomeStyle Decor)',
    uploadDate: 'Mar 24, 2026',
    iconColor: 'purple',
  },
  {
    id: 'doc-003',
    documentName: 'Bank Account Statement',
    sellerInfo: 'Suresh Krishnan (SpiceLand Traders)',
    uploadDate: 'Mar 23, 2026',
    iconColor: 'green',
  },
  {
    id: 'doc-004',
    documentName: 'Trade License',
    sellerInfo: 'Deepa Agarwal (CraftVilla Artisans)',
    uploadDate: 'Mar 22, 2026',
    iconColor: 'orange',
  },
  {
    id: 'doc-005',
    documentName: 'Address Proof (Aadhaar)',
    sellerInfo: 'Arjun Mehta (FitGear Sports)',
    uploadDate: 'Mar 21, 2026',
    iconColor: 'red',
  },
];
